In [1]:
import pandas as pd

In [3]:
import sys
print(sys.executable)

/workspaces/docker-studies/pipeline/.venv/bin/python3

In [4]:
prefix = "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow"
url = f"{prefix}/yellow_tripdata_2019-10.csv.gz"

In [5]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

In [6]:
df["tpep_pickup_datetime"]

0     2019-10-01 00:19:55
1     2019-10-01 00:40:19
2     2019-10-01 00:06:52
3     2019-10-01 00:36:08
4     2019-10-01 00:36:08
              ...
995   2019-10-01 00:02:56
996   2019-10-01 00:16:01
997   2019-10-01 00:27:10
998   2019-10-01 00:08:36
999   2019-10-01 00:21:15
Name: tpep_pickup_datetime, Length: 1000, dtype: datetime64[ns]

In [7]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2019-10-01 00:19:55,2019-10-01 00:23:57,1,0.40,1,N,48,163,2,4.5,3.0,0.5,0.0,0.00,0.3,8.30,2.5
1,1,2019-10-01 00:40:19,2019-10-01 00:55:17,2,4.30,1,N,144,141,1,14.5,3.0,0.5,2.0,0.00,0.3,20.30,2.5
2,1,2019-10-01 00:06:52,2019-10-01 00:21:23,1,5.00,1,N,137,80,1,17.0,3.0,0.5,5.2,0.00,0.3,26.00,2.5
3,2,2019-10-01 00:36:08,2019-10-01 00:36:15,1,0.00,1,N,25,25,4,-2.5,-0.5,-0.5,0.0,0.00,-0.3,-3.80,0.0
4,2,2019-10-01 00:36:08,2019-10-01 00:36:15,1,0.00,1,N,25,25,2,2.5,0.5,0.5,0.0,0.00,0.3,3.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2,2019-10-01 00:02:56,2019-10-01 00:10:32,1,1.14,1,N,158,234,1,7.0,0.5,0.5,5.2,0.00,0.3,16.00,2.5
996,2,2019-10-01 00:16:01,2019-10-01 00:27:09,1,2.44,1,N,79,68,2,10.0,0.5,0.5,0.0,0.00,0.3,13.80,2.5
997,2,2019-10-01 00:27:10,2019-10-01 00:45:09,1,10.13,1,N,138,183,1,29.0,0.5,0.5,5.5,6.12,0.3,41.92,0.0
998,1,2019-10-01 00:08:36,2019-10-01 00:14:18,1,1.50,1,N,48,68,2,7.0,3.0,0.5,0.0,0.00,0.3,10.80,2.5
999,1,2019-10-01 00:21:15,2019-10-01 00:30:33,1,1.70,1,N,164,79,2,8.5,3.0,0.5,0.0,0.00,0.3,12.30,2.5

In [8]:
from sqlalchemy import create_engine
engine = create_engine("postgresql://root:root@localhost:5432/nyc_taxi")

In [11]:
df.head(0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [39]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator = True,
    chunksize = 100000
)

In [40]:
from tqdm.auto import tqdm

In [ ]:
for df_chunks in tqdm(df_iter):
   df_chunks.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

0it [00:00, ?it/s]

In [38]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
7200000,<NA>,2019-10-23 15:46:38,2019-10-23 16:35:28,<NA>,11.26,<NA>,<NA>,233,78,<NA>,32.37,2.75,0.0,0.0,6.12,0.3,41.54,0.0
7200001,<NA>,2019-10-23 15:09:25,2019-10-23 15:52:42,<NA>,9.63,<NA>,<NA>,233,188,<NA>,28.26,2.75,0.0,0.0,0.00,0.3,31.31,0.0
7200002,<NA>,2019-10-23 15:39:00,2019-10-23 16:08:00,<NA>,9.26,<NA>,<NA>,64,258,<NA>,32.31,2.75,0.5,0.0,0.00,0.3,35.86,0.0
7200003,<NA>,2019-10-23 15:07:14,2019-10-23 16:19:34,<NA>,21.31,<NA>,<NA>,88,81,<NA>,59.41,2.75,0.0,0.0,0.00,0.3,62.46,0.0
7200004,<NA>,2019-10-23 15:06:00,2019-10-23 15:52:00,<NA>,11.64,<NA>,<NA>,137,89,<NA>,42.23,2.75,0.5,0.0,6.12,0.3,51.90,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7213886,<NA>,2019-10-31 23:20:00,2019-10-31 23:56:00,<NA>,19.53,<NA>,<NA>,77,119,<NA>,63.83,2.75,0.5,0.0,6.12,0.3,73.50,0.0
7213887,<NA>,2019-10-31 23:42:00,2019-11-01 00:07:00,<NA>,4.96,<NA>,<NA>,238,137,<NA>,28.95,2.75,0.5,0.0,0.00,0.3,32.50,0.0
7213888,<NA>,2019-10-31 23:50:35,2019-11-01 00:08:45,<NA>,4.63,<NA>,<NA>,186,166,<NA>,29.26,2.75,0.0,0.0,0.00,0.3,32.31,0.0
7213889,<NA>,2019-10-31 23:29:26,2019-10-31 23:59:15,<NA>,17.49,<NA>,<NA>,45,122,<NA>,54.25,2.75,0.0,0.0,6.12,0.3,63.42,0.0
7213890,<NA>,2019-10-31 23:52:00,2019-11-01 00:39:00,<NA>,15.97,<NA>,<NA>,140,91,<NA>,39.62,2.75,0.5,0.0,6.12,0.3,49.29,0.0